// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2VmR62qZ1ypG07kS9TaBcllWmGH6Lhyg',
    appId: '1:148874881712:web:7dc71555abad5bbd1d6975',
    messagingSenderId: '148874881712',
    projectId: 'victuna-8138d',
    authDomain: 'victuna-8138d.firebaseapp.com',
    storageBucket: 'victuna-8138d.firebasestorage.app',
    measurementId: 'G-X6F5Y5HRTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKh48fnIkkiPquyEOnHKBFaSWozJLXw4',
    appId: '1:148874881712:android:bb024d85073fcd6a1d6975',
    messagingSenderId: '148874881712',
    projectId: 'victuna-8138d',
    storageBucket: 'victuna-8138d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jN9VsqQZ5ytHG6FKV9cw6fpuvldeq6Y',
    appId: '1:148874881712:ios:de451eb8c442426c1d6975',
    messagingSenderId: '148874881712',
    projectId: 'victuna-8138d',
    storageBucket: 'victuna-8138d.firebasestorage.app',
    iosClientId:
        '148874881712-36fei39p6lju3iihr6t4ailk7mke0lsf.apps.googleusercontent.com',
    iosBundleId: 'za.medi.vicuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jN9VsqQZ5ytHG6FKV9cw6fpuvldeq6Y',
    appId: '1:148874881712:ios:c5a1538b508962201d6975',
    messagingSenderId: '148874881712',
    projectId: 'victuna-8138d',
    storageBucket: 'victuna-8138d.firebasestorage.app',
    iosClientId:
        '148874881712-8fiiej8qr6ni7evl35ufv8rdfsip7b77.apps.googleusercontent.com',
    iosBundleId: 'za.medi.vicuna.vicuna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2VmR62qZ1ypG07kS9TaBcllWmGH6Lhyg',
    appId: '1:148874881712:web:69e8ec994a79098f1d6975',
    messagingSenderId: '148874881712',
    projectId: 'victuna-8138d',
    authDomain: 'victuna-8138d.firebaseapp.com',
    storageBucket: 'victuna-8138d.firebasestorage.app',
    measurementId: 'G-2LXD8RMN1Y',
  );
}
