lane  :deploy do |options|
  # Retrieve the build number passed from Jenkins
  # If it's missing (local build), it defaults to 1
  bn = options[:build_number] || "1"
  
  # Build the Flutter App Bundle using the dynamic build number
  sh("flutter build appbundle --release --build-number=#{bn}")


  upload_to_play_store(
    track: "closed",
    aab: "app/outputs/bundle/release/app-release.aab",
    json_key_data: ENV["GPLAY_JSON_KEY"]
  )
end