lane :check_path do
  # This tries to fetch from Appfile
  path = CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file)
  
  if path.nil?
    UI.error("❌ Appfile is NOT returning a value for json_key_file. Check your Appfile syntax.")
  else
    UI.message("Fastlane found the path in Appfile: #{path}")
    expanded_path = File.expand_path(path)
    UI.message("Full absolute path: #{expanded_path}")
    
    if File.exist?(path)
      UI.success("✅ SUCCESS: File exists at that location!")
    else
      UI.error("❌ ERROR: Path is set, but the file is missing at: #{expanded_path}")
    end
  end
end

lane  :deploy do |options|
  # Retrieve the build number passed from Jenkins
  # If it's missing (local build), it defaults to 1
  bn = options[:build_number] || "1"
  
  # Build the Flutter App Bundle using the dynamic build number
  sh("flutter build appbundle --release --build-number=#{bn}")


  upload_to_play_store(
    track: "closed",
    aab: "../build/app/outputs/bundle/release/app-release.aab"
  )
end
